# Generated by Django 6.1.1 on 2026-10-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the task')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', help_text='Current status', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Priority level', max_length=10)),
                ('due_date', models.DateField(blank=True, help_text='Optional completion deadline (YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when task was last updated')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
